# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: dhar's blog
subtitle: Mostly Web Dev stuff...
description: "My name is Olivier Audard, I'm a Front-end developer at <a href='https://www.dailymotion.com/'>Dailymotion</a>, co-founder of  <a href='https://www.twitter.com/JSSophia'>@JSSophia</a>, Tai-Chi-Chuan student, Video Gamer, Role Playing Gamer"
author: Olivier Audard
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.dhar.fr
root: /
permalink: blog/:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: blog/tags
archive_dir: blog/archives
category_dir: blog/categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: [assets/**/*, jsweek/**/*]

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM Do YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cactus-dark

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# hexo-generator-feed plugin
feed:
    type: atom
    path: atom.xml

# hexo-generator-tag plugin
tag_generator:
  per_page: 0

# hexo-generator-sitemap plugin
sitemap:
  path: sitemap.xml
